dist: xenial
sudo: required
language: python
python:
  - 3.7

env:
  global:
  - PIPENV_IGNORE_VIRTUALENVS=1

install:
 - pipenv install --dev --deploy

script:
 - pipenv run coverage run --branch --source pyramid_heroku -m pytest pyramid_heroku
 - pipenv run coverage html
 - pipenv run coverage report --fail-under=97
